# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University_of_Colorado_Boulder/Fall2025/Embedded_AI/Prj/EMBD_FPGA/EMBD_FPGA.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University_of_Colorado_Boulder/Fall2025/Embedded_AI/Prj/EMBD_FPGA/EMBD_FPGA.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/University_of_Colorado_Boulder/Fall2025/Embedded_AI/Prj/EMBD_FPGA/EMBD_FPGA.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University_of_Colorado_Boulder/Fall2025/Embedded_AI/Prj/EMBD_FPGA/EMBD_FPGA.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
