// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module nn_inference_nn_inference_Pipeline_loop13 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_output3_0_address0,
        temp_output3_0_ce0,
        temp_output3_0_q0,
        max_idx_out,
        max_idx_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] temp_output3_0_address0;
output   temp_output3_0_ce0;
input  [31:0] temp_output3_0_q0;
output  [31:0] max_idx_out;
output   max_idx_out_ap_vld;

reg ap_idle;
reg temp_output3_0_ce0;
reg max_idx_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln95_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] i_reg_267;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] trunc_ln97_cast_fu_111_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] max_idx_fu_44;
wire   [31:0] max_idx_4_fu_215_p3;
wire    ap_loop_init;
reg   [31:0] max_val_fu_48;
wire   [31:0] max_val_2_fu_223_p3;
reg   [3:0] max_idx_1_fu_52;
reg   [3:0] ap_sig_allocacmp_i;
wire   [3:0] add_ln95_fu_105_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] bitcast_ln97_fu_128_p1;
wire   [31:0] bitcast_ln97_1_fu_146_p1;
wire   [7:0] tmp_4_fu_132_p4;
wire   [22:0] trunc_ln97_fu_142_p1;
wire   [0:0] icmp_ln97_1_fu_170_p2;
wire   [0:0] icmp_ln97_fu_164_p2;
wire   [7:0] tmp_5_fu_150_p4;
wire   [22:0] trunc_ln97_1_fu_160_p1;
wire   [0:0] icmp_ln97_3_fu_188_p2;
wire   [0:0] icmp_ln97_2_fu_182_p2;
wire   [0:0] tmp_6_fu_76_p2;
wire   [0:0] or_ln97_fu_176_p2;
wire   [0:0] and_ln97_fu_200_p2;
wire   [0:0] or_ln97_1_fu_194_p2;
wire   [0:0] and_ln97_1_fu_206_p2;
wire   [31:0] zext_ln97_fu_212_p1;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

nn_inference_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U369(
    .din0(temp_output3_0_q0),
    .din1(max_val_fu_48),
    .opcode(5'd2),
    .dout(tmp_6_fu_76_p2)
);

nn_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln95_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            max_idx_1_fu_52 <= add_ln95_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            max_idx_1_fu_52 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_idx_fu_44 <= 32'd4294967295;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            max_idx_fu_44 <= max_idx_4_fu_215_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_val_fu_48 <= 32'd3296328090;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            max_val_fu_48 <= max_val_2_fu_223_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_267 <= ap_sig_allocacmp_i;
    end
end

always @ (*) begin
    if (((icmp_ln95_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = max_idx_1_fu_52;
    end
end

always @ (*) begin
    if (((icmp_ln95_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_idx_out_ap_vld = 1'b1;
    end else begin
        max_idx_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_output3_0_ce0 = 1'b1;
    end else begin
        temp_output3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln95_fu_105_p2 = (ap_sig_allocacmp_i + 4'd1);

assign and_ln97_1_fu_206_p2 = (or_ln97_1_fu_194_p2 & and_ln97_fu_200_p2);

assign and_ln97_fu_200_p2 = (tmp_6_fu_76_p2 & or_ln97_fu_176_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln97_1_fu_146_p1 = max_val_fu_48;

assign bitcast_ln97_fu_128_p1 = temp_output3_0_q0;

assign icmp_ln95_fu_99_p2 = ((ap_sig_allocacmp_i == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln97_1_fu_170_p2 = ((trunc_ln97_fu_142_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_2_fu_182_p2 = ((tmp_5_fu_150_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln97_3_fu_188_p2 = ((trunc_ln97_1_fu_160_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_164_p2 = ((tmp_4_fu_132_p4 != 8'd255) ? 1'b1 : 1'b0);

assign max_idx_4_fu_215_p3 = ((and_ln97_1_fu_206_p2[0:0] == 1'b1) ? zext_ln97_fu_212_p1 : max_idx_fu_44);

assign max_idx_out = max_idx_fu_44;

assign max_val_2_fu_223_p3 = ((and_ln97_1_fu_206_p2[0:0] == 1'b1) ? temp_output3_0_q0 : max_val_fu_48);

assign or_ln97_1_fu_194_p2 = (icmp_ln97_3_fu_188_p2 | icmp_ln97_2_fu_182_p2);

assign or_ln97_fu_176_p2 = (icmp_ln97_fu_164_p2 | icmp_ln97_1_fu_170_p2);

assign temp_output3_0_address0 = trunc_ln97_cast_fu_111_p1;

assign tmp_4_fu_132_p4 = {{bitcast_ln97_fu_128_p1[30:23]}};

assign tmp_5_fu_150_p4 = {{bitcast_ln97_1_fu_146_p1[30:23]}};

assign trunc_ln97_1_fu_160_p1 = bitcast_ln97_1_fu_146_p1[22:0];

assign trunc_ln97_cast_fu_111_p1 = ap_sig_allocacmp_i;

assign trunc_ln97_fu_142_p1 = bitcast_ln97_fu_128_p1[22:0];

assign zext_ln97_fu_212_p1 = i_reg_267;

endmodule //nn_inference_nn_inference_Pipeline_loop13
