// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module nn_inference_nn_inference_Pipeline_col2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_output2_0_load_1,
        temp_output2_0_load_2,
        temp_output2_0_load_3,
        temp_output2_0_load_4,
        temp_output2_0_load_5,
        temp_output2_0_load_6,
        temp_output2_0_load_7,
        temp_output2_0_load_8,
        temp_output2_0_load_9,
        temp_output2_0_load_10,
        temp_output2_0_load_11,
        temp_output2_0_load_12,
        temp_output2_0_load_13,
        temp_output2_0_load_14,
        temp_output2_0_load_15,
        temp_output2_0_load_16,
        temp_output3_0_address0,
        temp_output3_0_ce0,
        temp_output3_0_we0,
        temp_output3_0_d0,
        grp_fu_1448_p_din0,
        grp_fu_1448_p_din1,
        grp_fu_1448_p_opcode,
        grp_fu_1448_p_dout0,
        grp_fu_1448_p_ce,
        grp_fu_1452_p_din0,
        grp_fu_1452_p_din1,
        grp_fu_1452_p_opcode,
        grp_fu_1452_p_dout0,
        grp_fu_1452_p_ce,
        grp_fu_1456_p_din0,
        grp_fu_1456_p_din1,
        grp_fu_1456_p_opcode,
        grp_fu_1456_p_dout0,
        grp_fu_1456_p_ce,
        grp_fu_1460_p_din0,
        grp_fu_1460_p_din1,
        grp_fu_1460_p_opcode,
        grp_fu_1460_p_dout0,
        grp_fu_1460_p_ce,
        grp_fu_1464_p_din0,
        grp_fu_1464_p_din1,
        grp_fu_1464_p_opcode,
        grp_fu_1464_p_dout0,
        grp_fu_1464_p_ce,
        grp_fu_1468_p_din0,
        grp_fu_1468_p_din1,
        grp_fu_1468_p_opcode,
        grp_fu_1468_p_dout0,
        grp_fu_1468_p_ce,
        grp_fu_1472_p_din0,
        grp_fu_1472_p_din1,
        grp_fu_1472_p_opcode,
        grp_fu_1472_p_dout0,
        grp_fu_1472_p_ce,
        grp_fu_1476_p_din0,
        grp_fu_1476_p_din1,
        grp_fu_1476_p_opcode,
        grp_fu_1476_p_dout0,
        grp_fu_1476_p_ce,
        grp_fu_1480_p_din0,
        grp_fu_1480_p_din1,
        grp_fu_1480_p_opcode,
        grp_fu_1480_p_dout0,
        grp_fu_1480_p_ce,
        grp_fu_1484_p_din0,
        grp_fu_1484_p_din1,
        grp_fu_1484_p_opcode,
        grp_fu_1484_p_dout0,
        grp_fu_1484_p_ce,
        grp_fu_1488_p_din0,
        grp_fu_1488_p_din1,
        grp_fu_1488_p_opcode,
        grp_fu_1488_p_dout0,
        grp_fu_1488_p_ce,
        grp_fu_1492_p_din0,
        grp_fu_1492_p_din1,
        grp_fu_1492_p_opcode,
        grp_fu_1492_p_dout0,
        grp_fu_1492_p_ce,
        grp_fu_1496_p_din0,
        grp_fu_1496_p_din1,
        grp_fu_1496_p_opcode,
        grp_fu_1496_p_dout0,
        grp_fu_1496_p_ce,
        grp_fu_1500_p_din0,
        grp_fu_1500_p_din1,
        grp_fu_1500_p_opcode,
        grp_fu_1500_p_dout0,
        grp_fu_1500_p_ce,
        grp_fu_1504_p_din0,
        grp_fu_1504_p_din1,
        grp_fu_1504_p_opcode,
        grp_fu_1504_p_dout0,
        grp_fu_1504_p_ce,
        grp_fu_1508_p_din0,
        grp_fu_1508_p_din1,
        grp_fu_1508_p_opcode,
        grp_fu_1508_p_dout0,
        grp_fu_1508_p_ce,
        grp_fu_1576_p_din0,
        grp_fu_1576_p_din1,
        grp_fu_1576_p_dout0,
        grp_fu_1576_p_ce,
        grp_fu_1580_p_din0,
        grp_fu_1580_p_din1,
        grp_fu_1580_p_dout0,
        grp_fu_1580_p_ce,
        grp_fu_1584_p_din0,
        grp_fu_1584_p_din1,
        grp_fu_1584_p_dout0,
        grp_fu_1584_p_ce,
        grp_fu_1588_p_din0,
        grp_fu_1588_p_din1,
        grp_fu_1588_p_dout0,
        grp_fu_1588_p_ce,
        grp_fu_1592_p_din0,
        grp_fu_1592_p_din1,
        grp_fu_1592_p_dout0,
        grp_fu_1592_p_ce,
        grp_fu_1596_p_din0,
        grp_fu_1596_p_din1,
        grp_fu_1596_p_dout0,
        grp_fu_1596_p_ce,
        grp_fu_1600_p_din0,
        grp_fu_1600_p_din1,
        grp_fu_1600_p_dout0,
        grp_fu_1600_p_ce,
        grp_fu_1604_p_din0,
        grp_fu_1604_p_din1,
        grp_fu_1604_p_dout0,
        grp_fu_1604_p_ce,
        grp_fu_1608_p_din0,
        grp_fu_1608_p_din1,
        grp_fu_1608_p_dout0,
        grp_fu_1608_p_ce,
        grp_fu_1612_p_din0,
        grp_fu_1612_p_din1,
        grp_fu_1612_p_dout0,
        grp_fu_1612_p_ce,
        grp_fu_1616_p_din0,
        grp_fu_1616_p_din1,
        grp_fu_1616_p_dout0,
        grp_fu_1616_p_ce,
        grp_fu_1620_p_din0,
        grp_fu_1620_p_din1,
        grp_fu_1620_p_dout0,
        grp_fu_1620_p_ce,
        grp_fu_1624_p_din0,
        grp_fu_1624_p_din1,
        grp_fu_1624_p_dout0,
        grp_fu_1624_p_ce,
        grp_fu_1628_p_din0,
        grp_fu_1628_p_din1,
        grp_fu_1628_p_dout0,
        grp_fu_1628_p_ce,
        grp_fu_1632_p_din0,
        grp_fu_1632_p_din1,
        grp_fu_1632_p_dout0,
        grp_fu_1632_p_ce,
        grp_fu_1636_p_din0,
        grp_fu_1636_p_din1,
        grp_fu_1636_p_dout0,
        grp_fu_1636_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] temp_output2_0_load_1;
input  [31:0] temp_output2_0_load_2;
input  [31:0] temp_output2_0_load_3;
input  [31:0] temp_output2_0_load_4;
input  [31:0] temp_output2_0_load_5;
input  [31:0] temp_output2_0_load_6;
input  [31:0] temp_output2_0_load_7;
input  [31:0] temp_output2_0_load_8;
input  [31:0] temp_output2_0_load_9;
input  [31:0] temp_output2_0_load_10;
input  [31:0] temp_output2_0_load_11;
input  [31:0] temp_output2_0_load_12;
input  [31:0] temp_output2_0_load_13;
input  [31:0] temp_output2_0_load_14;
input  [31:0] temp_output2_0_load_15;
input  [31:0] temp_output2_0_load_16;
output  [3:0] temp_output3_0_address0;
output   temp_output3_0_ce0;
output   temp_output3_0_we0;
output  [31:0] temp_output3_0_d0;
output  [31:0] grp_fu_1448_p_din0;
output  [31:0] grp_fu_1448_p_din1;
output  [1:0] grp_fu_1448_p_opcode;
input  [31:0] grp_fu_1448_p_dout0;
output   grp_fu_1448_p_ce;
output  [31:0] grp_fu_1452_p_din0;
output  [31:0] grp_fu_1452_p_din1;
output  [1:0] grp_fu_1452_p_opcode;
input  [31:0] grp_fu_1452_p_dout0;
output   grp_fu_1452_p_ce;
output  [31:0] grp_fu_1456_p_din0;
output  [31:0] grp_fu_1456_p_din1;
output  [1:0] grp_fu_1456_p_opcode;
input  [31:0] grp_fu_1456_p_dout0;
output   grp_fu_1456_p_ce;
output  [31:0] grp_fu_1460_p_din0;
output  [31:0] grp_fu_1460_p_din1;
output  [1:0] grp_fu_1460_p_opcode;
input  [31:0] grp_fu_1460_p_dout0;
output   grp_fu_1460_p_ce;
output  [31:0] grp_fu_1464_p_din0;
output  [31:0] grp_fu_1464_p_din1;
output  [1:0] grp_fu_1464_p_opcode;
input  [31:0] grp_fu_1464_p_dout0;
output   grp_fu_1464_p_ce;
output  [31:0] grp_fu_1468_p_din0;
output  [31:0] grp_fu_1468_p_din1;
output  [1:0] grp_fu_1468_p_opcode;
input  [31:0] grp_fu_1468_p_dout0;
output   grp_fu_1468_p_ce;
output  [31:0] grp_fu_1472_p_din0;
output  [31:0] grp_fu_1472_p_din1;
output  [1:0] grp_fu_1472_p_opcode;
input  [31:0] grp_fu_1472_p_dout0;
output   grp_fu_1472_p_ce;
output  [31:0] grp_fu_1476_p_din0;
output  [31:0] grp_fu_1476_p_din1;
output  [1:0] grp_fu_1476_p_opcode;
input  [31:0] grp_fu_1476_p_dout0;
output   grp_fu_1476_p_ce;
output  [31:0] grp_fu_1480_p_din0;
output  [31:0] grp_fu_1480_p_din1;
output  [1:0] grp_fu_1480_p_opcode;
input  [31:0] grp_fu_1480_p_dout0;
output   grp_fu_1480_p_ce;
output  [31:0] grp_fu_1484_p_din0;
output  [31:0] grp_fu_1484_p_din1;
output  [1:0] grp_fu_1484_p_opcode;
input  [31:0] grp_fu_1484_p_dout0;
output   grp_fu_1484_p_ce;
output  [31:0] grp_fu_1488_p_din0;
output  [31:0] grp_fu_1488_p_din1;
output  [1:0] grp_fu_1488_p_opcode;
input  [31:0] grp_fu_1488_p_dout0;
output   grp_fu_1488_p_ce;
output  [31:0] grp_fu_1492_p_din0;
output  [31:0] grp_fu_1492_p_din1;
output  [1:0] grp_fu_1492_p_opcode;
input  [31:0] grp_fu_1492_p_dout0;
output   grp_fu_1492_p_ce;
output  [31:0] grp_fu_1496_p_din0;
output  [31:0] grp_fu_1496_p_din1;
output  [1:0] grp_fu_1496_p_opcode;
input  [31:0] grp_fu_1496_p_dout0;
output   grp_fu_1496_p_ce;
output  [31:0] grp_fu_1500_p_din0;
output  [31:0] grp_fu_1500_p_din1;
output  [1:0] grp_fu_1500_p_opcode;
input  [31:0] grp_fu_1500_p_dout0;
output   grp_fu_1500_p_ce;
output  [31:0] grp_fu_1504_p_din0;
output  [31:0] grp_fu_1504_p_din1;
output  [1:0] grp_fu_1504_p_opcode;
input  [31:0] grp_fu_1504_p_dout0;
output   grp_fu_1504_p_ce;
output  [31:0] grp_fu_1508_p_din0;
output  [31:0] grp_fu_1508_p_din1;
output  [1:0] grp_fu_1508_p_opcode;
input  [31:0] grp_fu_1508_p_dout0;
output   grp_fu_1508_p_ce;
output  [31:0] grp_fu_1576_p_din0;
output  [31:0] grp_fu_1576_p_din1;
input  [31:0] grp_fu_1576_p_dout0;
output   grp_fu_1576_p_ce;
output  [31:0] grp_fu_1580_p_din0;
output  [31:0] grp_fu_1580_p_din1;
input  [31:0] grp_fu_1580_p_dout0;
output   grp_fu_1580_p_ce;
output  [31:0] grp_fu_1584_p_din0;
output  [31:0] grp_fu_1584_p_din1;
input  [31:0] grp_fu_1584_p_dout0;
output   grp_fu_1584_p_ce;
output  [31:0] grp_fu_1588_p_din0;
output  [31:0] grp_fu_1588_p_din1;
input  [31:0] grp_fu_1588_p_dout0;
output   grp_fu_1588_p_ce;
output  [31:0] grp_fu_1592_p_din0;
output  [31:0] grp_fu_1592_p_din1;
input  [31:0] grp_fu_1592_p_dout0;
output   grp_fu_1592_p_ce;
output  [31:0] grp_fu_1596_p_din0;
output  [31:0] grp_fu_1596_p_din1;
input  [31:0] grp_fu_1596_p_dout0;
output   grp_fu_1596_p_ce;
output  [31:0] grp_fu_1600_p_din0;
output  [31:0] grp_fu_1600_p_din1;
input  [31:0] grp_fu_1600_p_dout0;
output   grp_fu_1600_p_ce;
output  [31:0] grp_fu_1604_p_din0;
output  [31:0] grp_fu_1604_p_din1;
input  [31:0] grp_fu_1604_p_dout0;
output   grp_fu_1604_p_ce;
output  [31:0] grp_fu_1608_p_din0;
output  [31:0] grp_fu_1608_p_din1;
input  [31:0] grp_fu_1608_p_dout0;
output   grp_fu_1608_p_ce;
output  [31:0] grp_fu_1612_p_din0;
output  [31:0] grp_fu_1612_p_din1;
input  [31:0] grp_fu_1612_p_dout0;
output   grp_fu_1612_p_ce;
output  [31:0] grp_fu_1616_p_din0;
output  [31:0] grp_fu_1616_p_din1;
input  [31:0] grp_fu_1616_p_dout0;
output   grp_fu_1616_p_ce;
output  [31:0] grp_fu_1620_p_din0;
output  [31:0] grp_fu_1620_p_din1;
input  [31:0] grp_fu_1620_p_dout0;
output   grp_fu_1620_p_ce;
output  [31:0] grp_fu_1624_p_din0;
output  [31:0] grp_fu_1624_p_din1;
input  [31:0] grp_fu_1624_p_dout0;
output   grp_fu_1624_p_ce;
output  [31:0] grp_fu_1628_p_din0;
output  [31:0] grp_fu_1628_p_din1;
input  [31:0] grp_fu_1628_p_dout0;
output   grp_fu_1628_p_ce;
output  [31:0] grp_fu_1632_p_din0;
output  [31:0] grp_fu_1632_p_din1;
input  [31:0] grp_fu_1632_p_dout0;
output   grp_fu_1632_p_ce;
output  [31:0] grp_fu_1636_p_din0;
output  [31:0] grp_fu_1636_p_din1;
input  [31:0] grp_fu_1636_p_dout0;
output   grp_fu_1636_p_ce;

reg ap_idle;
reg temp_output3_0_ce0;
reg temp_output3_0_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln45_fu_571_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] layer3_weights_0_address0;
reg    layer3_weights_0_ce0;
wire   [31:0] layer3_weights_0_q0;
wire   [3:0] layer3_weights_1_address0;
reg    layer3_weights_1_ce0;
wire   [31:0] layer3_weights_1_q0;
wire   [3:0] layer3_weights_2_address0;
reg    layer3_weights_2_ce0;
wire   [31:0] layer3_weights_2_q0;
wire   [3:0] layer3_weights_3_address0;
reg    layer3_weights_3_ce0;
wire   [31:0] layer3_weights_3_q0;
wire   [3:0] layer3_weights_4_address0;
reg    layer3_weights_4_ce0;
wire   [31:0] layer3_weights_4_q0;
wire   [3:0] layer3_weights_5_address0;
reg    layer3_weights_5_ce0;
wire   [31:0] layer3_weights_5_q0;
wire   [3:0] layer3_weights_6_address0;
reg    layer3_weights_6_ce0;
wire   [31:0] layer3_weights_6_q0;
wire   [3:0] layer3_weights_7_address0;
reg    layer3_weights_7_ce0;
wire   [31:0] layer3_weights_7_q0;
wire   [3:0] layer3_weights_8_address0;
reg    layer3_weights_8_ce0;
wire   [31:0] layer3_weights_8_q0;
wire   [3:0] layer3_weights_9_address0;
reg    layer3_weights_9_ce0;
wire   [31:0] layer3_weights_9_q0;
wire   [3:0] layer3_weights_10_address0;
reg    layer3_weights_10_ce0;
wire   [31:0] layer3_weights_10_q0;
wire   [3:0] layer3_weights_11_address0;
reg    layer3_weights_11_ce0;
wire   [31:0] layer3_weights_11_q0;
wire   [3:0] layer3_weights_12_address0;
reg    layer3_weights_12_ce0;
wire   [31:0] layer3_weights_12_q0;
wire   [3:0] layer3_weights_13_address0;
reg    layer3_weights_13_ce0;
wire   [31:0] layer3_weights_13_q0;
wire   [3:0] layer3_weights_14_address0;
reg    layer3_weights_14_ce0;
wire   [31:0] layer3_weights_14_q0;
wire   [3:0] layer3_weights_15_address0;
reg    layer3_weights_15_ce0;
wire   [31:0] layer3_weights_15_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] j_1_cast_fu_583_p1;
reg   [63:0] j_1_cast_reg_684;
reg   [63:0] j_1_cast_reg_684_pp0_iter1_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter2_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter3_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter4_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter5_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter6_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter7_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter8_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter9_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter10_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter11_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter12_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter13_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter14_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter15_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter16_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter17_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter18_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter19_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter20_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter21_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter22_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter23_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter24_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter25_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter26_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter27_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter28_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter29_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter30_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter31_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter32_reg;
reg   [63:0] j_1_cast_reg_684_pp0_iter33_reg;
reg   [31:0] mul_i1_reg_714;
reg   [31:0] sum_3_reg_729;
reg   [31:0] mul_i1_1_reg_734;
reg   [31:0] sum_3_1_reg_749;
reg   [31:0] mul_i1_2_reg_754;
reg   [31:0] sum_3_2_reg_769;
reg   [31:0] mul_i1_3_reg_774;
reg   [31:0] sum_3_3_reg_789;
reg   [31:0] mul_i1_4_reg_794;
reg   [31:0] sum_3_4_reg_809;
reg   [31:0] mul_i1_5_reg_814;
reg   [31:0] sum_3_5_reg_829;
reg   [31:0] mul_i1_6_reg_834;
reg   [31:0] sum_3_6_reg_849;
reg   [31:0] mul_i1_7_reg_854;
reg   [31:0] sum_3_7_reg_869;
reg   [31:0] mul_i1_8_reg_874;
reg   [31:0] sum_3_8_reg_889;
reg   [31:0] mul_i1_9_reg_894;
reg   [31:0] sum_3_9_reg_909;
reg   [31:0] mul_i1_s_reg_914;
reg   [31:0] sum_3_s_reg_929;
reg   [31:0] mul_i1_10_reg_934;
reg   [31:0] sum_3_10_reg_949;
reg   [31:0] mul_i1_11_reg_954;
reg   [31:0] sum_3_11_reg_969;
reg   [31:0] mul_i1_12_reg_974;
reg   [31:0] sum_3_12_reg_989;
reg   [31:0] mul_i1_13_reg_994;
reg   [31:0] sum_3_13_reg_1009;
reg   [31:0] mul_i1_14_reg_1014;
wire    ap_block_pp0_stage0;
reg   [3:0] j_fu_96;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_1;
wire   [3:0] add_ln45_fu_577_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_done_reg = 1'b0;
end

nn_inference_nn_inference_Pipeline_col2_layer3_weights_0 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_0_address0),
    .ce0(layer3_weights_0_ce0),
    .q0(layer3_weights_0_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_1 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_1_address0),
    .ce0(layer3_weights_1_ce0),
    .q0(layer3_weights_1_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_2 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_2_address0),
    .ce0(layer3_weights_2_ce0),
    .q0(layer3_weights_2_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_3 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_3_address0),
    .ce0(layer3_weights_3_ce0),
    .q0(layer3_weights_3_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_4 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_4_address0),
    .ce0(layer3_weights_4_ce0),
    .q0(layer3_weights_4_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_5 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_5_address0),
    .ce0(layer3_weights_5_ce0),
    .q0(layer3_weights_5_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_6 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_6_address0),
    .ce0(layer3_weights_6_ce0),
    .q0(layer3_weights_6_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_7 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_7_address0),
    .ce0(layer3_weights_7_ce0),
    .q0(layer3_weights_7_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_8 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_8_address0),
    .ce0(layer3_weights_8_ce0),
    .q0(layer3_weights_8_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_9 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_9_address0),
    .ce0(layer3_weights_9_ce0),
    .q0(layer3_weights_9_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_10 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_10_address0),
    .ce0(layer3_weights_10_ce0),
    .q0(layer3_weights_10_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_11 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_11_address0),
    .ce0(layer3_weights_11_ce0),
    .q0(layer3_weights_11_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_12 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_12_address0),
    .ce0(layer3_weights_12_ce0),
    .q0(layer3_weights_12_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_13 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_13_address0),
    .ce0(layer3_weights_13_ce0),
    .q0(layer3_weights_13_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_14 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_14_address0),
    .ce0(layer3_weights_14_ce0),
    .q0(layer3_weights_14_q0)
);

nn_inference_nn_inference_Pipeline_col2_layer3_weights_15 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
layer3_weights_15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer3_weights_15_address0),
    .ce0(layer3_weights_15_ce0),
    .q0(layer3_weights_15_q0)
);

nn_inference_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter33_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln45_fu_571_p2 == 1'd0))) begin
            j_fu_96 <= add_ln45_fu_577_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_96 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        j_1_cast_reg_684_pp0_iter10_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter9_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter11_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter10_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter12_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter11_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter13_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter12_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter14_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter13_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter15_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter14_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter16_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter15_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter17_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter16_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter18_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter17_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter19_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter18_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter20_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter19_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter21_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter20_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter22_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter21_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter23_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter22_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter24_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter23_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter25_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter24_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter26_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter25_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter27_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter26_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter28_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter27_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter29_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter28_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter2_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter1_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter30_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter29_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter31_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter30_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter32_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter31_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter33_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter32_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter3_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter2_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter4_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter3_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter5_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter4_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter6_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter5_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter7_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter6_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter8_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter7_reg[3 : 0];
        j_1_cast_reg_684_pp0_iter9_reg[3 : 0] <= j_1_cast_reg_684_pp0_iter8_reg[3 : 0];
        mul_i1_10_reg_934 <= grp_fu_1620_p_dout0;
        mul_i1_11_reg_954 <= grp_fu_1624_p_dout0;
        mul_i1_12_reg_974 <= grp_fu_1628_p_dout0;
        mul_i1_13_reg_994 <= grp_fu_1632_p_dout0;
        mul_i1_14_reg_1014 <= grp_fu_1636_p_dout0;
        mul_i1_1_reg_734 <= grp_fu_1580_p_dout0;
        mul_i1_2_reg_754 <= grp_fu_1584_p_dout0;
        mul_i1_3_reg_774 <= grp_fu_1588_p_dout0;
        mul_i1_4_reg_794 <= grp_fu_1592_p_dout0;
        mul_i1_5_reg_814 <= grp_fu_1596_p_dout0;
        mul_i1_6_reg_834 <= grp_fu_1600_p_dout0;
        mul_i1_7_reg_854 <= grp_fu_1604_p_dout0;
        mul_i1_8_reg_874 <= grp_fu_1608_p_dout0;
        mul_i1_9_reg_894 <= grp_fu_1612_p_dout0;
        mul_i1_reg_714 <= grp_fu_1576_p_dout0;
        mul_i1_s_reg_914 <= grp_fu_1616_p_dout0;
        sum_3_10_reg_949 <= grp_fu_1492_p_dout0;
        sum_3_11_reg_969 <= grp_fu_1496_p_dout0;
        sum_3_12_reg_989 <= grp_fu_1500_p_dout0;
        sum_3_13_reg_1009 <= grp_fu_1504_p_dout0;
        sum_3_1_reg_749 <= grp_fu_1452_p_dout0;
        sum_3_2_reg_769 <= grp_fu_1456_p_dout0;
        sum_3_3_reg_789 <= grp_fu_1460_p_dout0;
        sum_3_4_reg_809 <= grp_fu_1464_p_dout0;
        sum_3_5_reg_829 <= grp_fu_1468_p_dout0;
        sum_3_6_reg_849 <= grp_fu_1472_p_dout0;
        sum_3_7_reg_869 <= grp_fu_1476_p_dout0;
        sum_3_8_reg_889 <= grp_fu_1480_p_dout0;
        sum_3_9_reg_909 <= grp_fu_1484_p_dout0;
        sum_3_reg_729 <= grp_fu_1448_p_dout0;
        sum_3_s_reg_929 <= grp_fu_1488_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        j_1_cast_reg_684_pp0_iter1_reg[3 : 0] <= j_1_cast_reg_684[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln45_fu_571_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_1_cast_reg_684[3 : 0] <= j_1_cast_fu_583_p1[3 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln45_fu_571_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter33_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_96;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_0_ce0 = 1'b1;
    end else begin
        layer3_weights_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_10_ce0 = 1'b1;
    end else begin
        layer3_weights_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_11_ce0 = 1'b1;
    end else begin
        layer3_weights_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_12_ce0 = 1'b1;
    end else begin
        layer3_weights_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_13_ce0 = 1'b1;
    end else begin
        layer3_weights_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter28 == 1'b1))) begin
        layer3_weights_14_ce0 = 1'b1;
    end else begin
        layer3_weights_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        layer3_weights_15_ce0 = 1'b1;
    end else begin
        layer3_weights_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_1_ce0 = 1'b1;
    end else begin
        layer3_weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_2_ce0 = 1'b1;
    end else begin
        layer3_weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_3_ce0 = 1'b1;
    end else begin
        layer3_weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_4_ce0 = 1'b1;
    end else begin
        layer3_weights_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_5_ce0 = 1'b1;
    end else begin
        layer3_weights_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_6_ce0 = 1'b1;
    end else begin
        layer3_weights_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_7_ce0 = 1'b1;
    end else begin
        layer3_weights_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_8_ce0 = 1'b1;
    end else begin
        layer3_weights_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer3_weights_9_ce0 = 1'b1;
    end else begin
        layer3_weights_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        temp_output3_0_ce0 = 1'b1;
    end else begin
        temp_output3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        temp_output3_0_we0 = 1'b1;
    end else begin
        temp_output3_0_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln45_fu_577_p2 = (ap_sig_allocacmp_j_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_1448_p_ce = 1'b1;

assign grp_fu_1448_p_din0 = mul_i1_reg_714;

assign grp_fu_1448_p_din1 = 32'd0;

assign grp_fu_1448_p_opcode = 2'd0;

assign grp_fu_1452_p_ce = 1'b1;

assign grp_fu_1452_p_din0 = sum_3_reg_729;

assign grp_fu_1452_p_din1 = mul_i1_1_reg_734;

assign grp_fu_1452_p_opcode = 2'd0;

assign grp_fu_1456_p_ce = 1'b1;

assign grp_fu_1456_p_din0 = sum_3_1_reg_749;

assign grp_fu_1456_p_din1 = mul_i1_2_reg_754;

assign grp_fu_1456_p_opcode = 2'd0;

assign grp_fu_1460_p_ce = 1'b1;

assign grp_fu_1460_p_din0 = sum_3_2_reg_769;

assign grp_fu_1460_p_din1 = mul_i1_3_reg_774;

assign grp_fu_1460_p_opcode = 2'd0;

assign grp_fu_1464_p_ce = 1'b1;

assign grp_fu_1464_p_din0 = sum_3_3_reg_789;

assign grp_fu_1464_p_din1 = mul_i1_4_reg_794;

assign grp_fu_1464_p_opcode = 2'd0;

assign grp_fu_1468_p_ce = 1'b1;

assign grp_fu_1468_p_din0 = sum_3_4_reg_809;

assign grp_fu_1468_p_din1 = mul_i1_5_reg_814;

assign grp_fu_1468_p_opcode = 2'd0;

assign grp_fu_1472_p_ce = 1'b1;

assign grp_fu_1472_p_din0 = sum_3_5_reg_829;

assign grp_fu_1472_p_din1 = mul_i1_6_reg_834;

assign grp_fu_1472_p_opcode = 2'd0;

assign grp_fu_1476_p_ce = 1'b1;

assign grp_fu_1476_p_din0 = sum_3_6_reg_849;

assign grp_fu_1476_p_din1 = mul_i1_7_reg_854;

assign grp_fu_1476_p_opcode = 2'd0;

assign grp_fu_1480_p_ce = 1'b1;

assign grp_fu_1480_p_din0 = sum_3_7_reg_869;

assign grp_fu_1480_p_din1 = mul_i1_8_reg_874;

assign grp_fu_1480_p_opcode = 2'd0;

assign grp_fu_1484_p_ce = 1'b1;

assign grp_fu_1484_p_din0 = sum_3_8_reg_889;

assign grp_fu_1484_p_din1 = mul_i1_9_reg_894;

assign grp_fu_1484_p_opcode = 2'd0;

assign grp_fu_1488_p_ce = 1'b1;

assign grp_fu_1488_p_din0 = sum_3_9_reg_909;

assign grp_fu_1488_p_din1 = mul_i1_s_reg_914;

assign grp_fu_1488_p_opcode = 2'd0;

assign grp_fu_1492_p_ce = 1'b1;

assign grp_fu_1492_p_din0 = sum_3_s_reg_929;

assign grp_fu_1492_p_din1 = mul_i1_10_reg_934;

assign grp_fu_1492_p_opcode = 2'd0;

assign grp_fu_1496_p_ce = 1'b1;

assign grp_fu_1496_p_din0 = sum_3_10_reg_949;

assign grp_fu_1496_p_din1 = mul_i1_11_reg_954;

assign grp_fu_1496_p_opcode = 2'd0;

assign grp_fu_1500_p_ce = 1'b1;

assign grp_fu_1500_p_din0 = sum_3_11_reg_969;

assign grp_fu_1500_p_din1 = mul_i1_12_reg_974;

assign grp_fu_1500_p_opcode = 2'd0;

assign grp_fu_1504_p_ce = 1'b1;

assign grp_fu_1504_p_din0 = sum_3_12_reg_989;

assign grp_fu_1504_p_din1 = mul_i1_13_reg_994;

assign grp_fu_1504_p_opcode = 2'd0;

assign grp_fu_1508_p_ce = 1'b1;

assign grp_fu_1508_p_din0 = sum_3_13_reg_1009;

assign grp_fu_1508_p_din1 = mul_i1_14_reg_1014;

assign grp_fu_1508_p_opcode = 2'd0;

assign grp_fu_1576_p_ce = 1'b1;

assign grp_fu_1576_p_din0 = temp_output2_0_load_1;

assign grp_fu_1576_p_din1 = layer3_weights_0_q0;

assign grp_fu_1580_p_ce = 1'b1;

assign grp_fu_1580_p_din0 = temp_output2_0_load_2;

assign grp_fu_1580_p_din1 = layer3_weights_1_q0;

assign grp_fu_1584_p_ce = 1'b1;

assign grp_fu_1584_p_din0 = temp_output2_0_load_3;

assign grp_fu_1584_p_din1 = layer3_weights_2_q0;

assign grp_fu_1588_p_ce = 1'b1;

assign grp_fu_1588_p_din0 = temp_output2_0_load_4;

assign grp_fu_1588_p_din1 = layer3_weights_3_q0;

assign grp_fu_1592_p_ce = 1'b1;

assign grp_fu_1592_p_din0 = temp_output2_0_load_5;

assign grp_fu_1592_p_din1 = layer3_weights_4_q0;

assign grp_fu_1596_p_ce = 1'b1;

assign grp_fu_1596_p_din0 = temp_output2_0_load_6;

assign grp_fu_1596_p_din1 = layer3_weights_5_q0;

assign grp_fu_1600_p_ce = 1'b1;

assign grp_fu_1600_p_din0 = temp_output2_0_load_7;

assign grp_fu_1600_p_din1 = layer3_weights_6_q0;

assign grp_fu_1604_p_ce = 1'b1;

assign grp_fu_1604_p_din0 = temp_output2_0_load_8;

assign grp_fu_1604_p_din1 = layer3_weights_7_q0;

assign grp_fu_1608_p_ce = 1'b1;

assign grp_fu_1608_p_din0 = temp_output2_0_load_9;

assign grp_fu_1608_p_din1 = layer3_weights_8_q0;

assign grp_fu_1612_p_ce = 1'b1;

assign grp_fu_1612_p_din0 = temp_output2_0_load_10;

assign grp_fu_1612_p_din1 = layer3_weights_9_q0;

assign grp_fu_1616_p_ce = 1'b1;

assign grp_fu_1616_p_din0 = temp_output2_0_load_11;

assign grp_fu_1616_p_din1 = layer3_weights_10_q0;

assign grp_fu_1620_p_ce = 1'b1;

assign grp_fu_1620_p_din0 = temp_output2_0_load_12;

assign grp_fu_1620_p_din1 = layer3_weights_11_q0;

assign grp_fu_1624_p_ce = 1'b1;

assign grp_fu_1624_p_din0 = temp_output2_0_load_13;

assign grp_fu_1624_p_din1 = layer3_weights_12_q0;

assign grp_fu_1628_p_ce = 1'b1;

assign grp_fu_1628_p_din0 = temp_output2_0_load_14;

assign grp_fu_1628_p_din1 = layer3_weights_13_q0;

assign grp_fu_1632_p_ce = 1'b1;

assign grp_fu_1632_p_din0 = temp_output2_0_load_15;

assign grp_fu_1632_p_din1 = layer3_weights_14_q0;

assign grp_fu_1636_p_ce = 1'b1;

assign grp_fu_1636_p_din0 = temp_output2_0_load_16;

assign grp_fu_1636_p_din1 = layer3_weights_15_q0;

assign icmp_ln45_fu_571_p2 = ((ap_sig_allocacmp_j_1 == 4'd10) ? 1'b1 : 1'b0);

assign j_1_cast_fu_583_p1 = ap_sig_allocacmp_j_1;

assign layer3_weights_0_address0 = j_1_cast_fu_583_p1;

assign layer3_weights_10_address0 = j_1_cast_reg_684_pp0_iter19_reg;

assign layer3_weights_11_address0 = j_1_cast_reg_684_pp0_iter21_reg;

assign layer3_weights_12_address0 = j_1_cast_reg_684_pp0_iter23_reg;

assign layer3_weights_13_address0 = j_1_cast_reg_684_pp0_iter25_reg;

assign layer3_weights_14_address0 = j_1_cast_reg_684_pp0_iter27_reg;

assign layer3_weights_15_address0 = j_1_cast_reg_684_pp0_iter29_reg;

assign layer3_weights_1_address0 = j_1_cast_reg_684_pp0_iter1_reg;

assign layer3_weights_2_address0 = j_1_cast_reg_684_pp0_iter3_reg;

assign layer3_weights_3_address0 = j_1_cast_reg_684_pp0_iter5_reg;

assign layer3_weights_4_address0 = j_1_cast_reg_684_pp0_iter7_reg;

assign layer3_weights_5_address0 = j_1_cast_reg_684_pp0_iter9_reg;

assign layer3_weights_6_address0 = j_1_cast_reg_684_pp0_iter11_reg;

assign layer3_weights_7_address0 = j_1_cast_reg_684_pp0_iter13_reg;

assign layer3_weights_8_address0 = j_1_cast_reg_684_pp0_iter15_reg;

assign layer3_weights_9_address0 = j_1_cast_reg_684_pp0_iter17_reg;

assign temp_output3_0_address0 = j_1_cast_reg_684_pp0_iter33_reg;

assign temp_output3_0_d0 = grp_fu_1508_p_dout0;

always @ (posedge ap_clk) begin
    j_1_cast_reg_684[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter3_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter4_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter5_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter6_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter7_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter8_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter9_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter10_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter11_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter12_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter13_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter14_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter15_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter16_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter17_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter18_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter19_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter20_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter21_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter22_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter23_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter24_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter25_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter26_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter27_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter28_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter29_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter30_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter31_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter32_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_1_cast_reg_684_pp0_iter33_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //nn_inference_nn_inference_Pipeline_col2
