-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nn_inference_nn_inference_Pipeline_col2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    temp_output2_0_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output2_0_load_16 : IN STD_LOGIC_VECTOR (31 downto 0);
    temp_output3_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    temp_output3_0_ce0 : OUT STD_LOGIC;
    temp_output3_0_we0 : OUT STD_LOGIC;
    temp_output3_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1448_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1448_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1448_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1448_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1448_p_ce : OUT STD_LOGIC;
    grp_fu_1452_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1452_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1452_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1452_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1452_p_ce : OUT STD_LOGIC;
    grp_fu_1456_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1456_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1456_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1456_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1456_p_ce : OUT STD_LOGIC;
    grp_fu_1460_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1460_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1460_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1460_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1460_p_ce : OUT STD_LOGIC;
    grp_fu_1464_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1464_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1464_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1464_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1464_p_ce : OUT STD_LOGIC;
    grp_fu_1468_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1468_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1468_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1468_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1468_p_ce : OUT STD_LOGIC;
    grp_fu_1472_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1472_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1472_p_ce : OUT STD_LOGIC;
    grp_fu_1476_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1476_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1476_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1476_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1476_p_ce : OUT STD_LOGIC;
    grp_fu_1480_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1480_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1480_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1480_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1480_p_ce : OUT STD_LOGIC;
    grp_fu_1484_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1484_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1484_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1484_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1484_p_ce : OUT STD_LOGIC;
    grp_fu_1488_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1488_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1488_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1488_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1488_p_ce : OUT STD_LOGIC;
    grp_fu_1492_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1492_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1492_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1492_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1492_p_ce : OUT STD_LOGIC;
    grp_fu_1496_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1496_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1496_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1496_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1496_p_ce : OUT STD_LOGIC;
    grp_fu_1500_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1500_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1500_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1500_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1500_p_ce : OUT STD_LOGIC;
    grp_fu_1504_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1504_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1504_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1504_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1504_p_ce : OUT STD_LOGIC;
    grp_fu_1508_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1508_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1508_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_1508_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1508_p_ce : OUT STD_LOGIC;
    grp_fu_1576_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1576_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1576_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1576_p_ce : OUT STD_LOGIC;
    grp_fu_1580_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1580_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1580_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1580_p_ce : OUT STD_LOGIC;
    grp_fu_1584_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1584_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1584_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1584_p_ce : OUT STD_LOGIC;
    grp_fu_1588_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1588_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1588_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1588_p_ce : OUT STD_LOGIC;
    grp_fu_1592_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1592_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1592_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1592_p_ce : OUT STD_LOGIC;
    grp_fu_1596_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1596_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1596_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1596_p_ce : OUT STD_LOGIC;
    grp_fu_1600_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1600_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1600_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1600_p_ce : OUT STD_LOGIC;
    grp_fu_1604_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1604_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1604_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1604_p_ce : OUT STD_LOGIC;
    grp_fu_1608_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1608_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1608_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1608_p_ce : OUT STD_LOGIC;
    grp_fu_1612_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1612_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1612_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1612_p_ce : OUT STD_LOGIC;
    grp_fu_1616_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1616_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1616_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1616_p_ce : OUT STD_LOGIC;
    grp_fu_1620_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1620_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1620_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1620_p_ce : OUT STD_LOGIC;
    grp_fu_1624_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1624_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1624_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1624_p_ce : OUT STD_LOGIC;
    grp_fu_1628_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1628_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1628_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1628_p_ce : OUT STD_LOGIC;
    grp_fu_1632_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1632_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1632_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1632_p_ce : OUT STD_LOGIC;
    grp_fu_1636_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1636_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1636_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_1636_p_ce : OUT STD_LOGIC );
end;


architecture behav of nn_inference_nn_inference_Pipeline_col2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter28 : BOOLEAN;
    signal ap_block_state30_pp0_stage0_iter29 : BOOLEAN;
    signal ap_block_state31_pp0_stage0_iter30 : BOOLEAN;
    signal ap_block_state32_pp0_stage0_iter31 : BOOLEAN;
    signal ap_block_state33_pp0_stage0_iter32 : BOOLEAN;
    signal ap_block_state34_pp0_stage0_iter33 : BOOLEAN;
    signal ap_block_state35_pp0_stage0_iter34 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln45_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer3_weights_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_0_ce0 : STD_LOGIC;
    signal layer3_weights_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_1_ce0 : STD_LOGIC;
    signal layer3_weights_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_2_ce0 : STD_LOGIC;
    signal layer3_weights_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_3_ce0 : STD_LOGIC;
    signal layer3_weights_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_4_ce0 : STD_LOGIC;
    signal layer3_weights_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_5_ce0 : STD_LOGIC;
    signal layer3_weights_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_6_ce0 : STD_LOGIC;
    signal layer3_weights_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_7_ce0 : STD_LOGIC;
    signal layer3_weights_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_8_ce0 : STD_LOGIC;
    signal layer3_weights_8_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_9_ce0 : STD_LOGIC;
    signal layer3_weights_9_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_10_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_10_ce0 : STD_LOGIC;
    signal layer3_weights_10_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_11_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_11_ce0 : STD_LOGIC;
    signal layer3_weights_11_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_12_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_12_ce0 : STD_LOGIC;
    signal layer3_weights_12_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_13_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_13_ce0 : STD_LOGIC;
    signal layer3_weights_13_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_14_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_14_ce0 : STD_LOGIC;
    signal layer3_weights_14_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal layer3_weights_15_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal layer3_weights_15_ce0 : STD_LOGIC;
    signal layer3_weights_15_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_1_cast_fu_583_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter16_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter17_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter18_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter19_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter20_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter21_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter22_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter23_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter24_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter25_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter26_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter27_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter28_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter29_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter30_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter31_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter32_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal j_1_cast_reg_684_pp0_iter33_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_i1_reg_714 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_reg_729 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_1_reg_734 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_1_reg_749 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_2_reg_754 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_2_reg_769 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_3_reg_774 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_3_reg_789 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_4_reg_794 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_4_reg_809 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_5_reg_814 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_5_reg_829 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_6_reg_834 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_6_reg_849 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_7_reg_854 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_7_reg_869 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_8_reg_874 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_8_reg_889 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_9_reg_894 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_9_reg_909 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_s_reg_914 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_s_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_10_reg_934 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_10_reg_949 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_11_reg_954 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_11_reg_969 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_12_reg_974 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_12_reg_989 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_13_reg_994 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_13_reg_1009 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_i1_14_reg_1014 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal j_fu_96 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln45_fu_577_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter27_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter28_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter29_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter30_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter31_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter32_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter33_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component nn_inference_fadd_32ns_32ns_32_2_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_fmul_32ns_32ns_32_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_3 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_4 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_5 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_6 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_7 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_8 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_9 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_10 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_11 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_12 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_13 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_14 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_nn_inference_Pipeline_col2_layer3_weights_15 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component nn_inference_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    layer3_weights_0_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_0
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_0_address0,
        ce0 => layer3_weights_0_ce0,
        q0 => layer3_weights_0_q0);

    layer3_weights_1_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_1
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_1_address0,
        ce0 => layer3_weights_1_ce0,
        q0 => layer3_weights_1_q0);

    layer3_weights_2_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_2
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_2_address0,
        ce0 => layer3_weights_2_ce0,
        q0 => layer3_weights_2_q0);

    layer3_weights_3_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_3
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_3_address0,
        ce0 => layer3_weights_3_ce0,
        q0 => layer3_weights_3_q0);

    layer3_weights_4_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_4
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_4_address0,
        ce0 => layer3_weights_4_ce0,
        q0 => layer3_weights_4_q0);

    layer3_weights_5_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_5
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_5_address0,
        ce0 => layer3_weights_5_ce0,
        q0 => layer3_weights_5_q0);

    layer3_weights_6_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_6
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_6_address0,
        ce0 => layer3_weights_6_ce0,
        q0 => layer3_weights_6_q0);

    layer3_weights_7_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_7
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_7_address0,
        ce0 => layer3_weights_7_ce0,
        q0 => layer3_weights_7_q0);

    layer3_weights_8_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_8
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_8_address0,
        ce0 => layer3_weights_8_ce0,
        q0 => layer3_weights_8_q0);

    layer3_weights_9_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_9
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_9_address0,
        ce0 => layer3_weights_9_ce0,
        q0 => layer3_weights_9_q0);

    layer3_weights_10_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_10
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_10_address0,
        ce0 => layer3_weights_10_ce0,
        q0 => layer3_weights_10_q0);

    layer3_weights_11_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_11
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_11_address0,
        ce0 => layer3_weights_11_ce0,
        q0 => layer3_weights_11_q0);

    layer3_weights_12_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_12
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_12_address0,
        ce0 => layer3_weights_12_ce0,
        q0 => layer3_weights_12_q0);

    layer3_weights_13_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_13
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_13_address0,
        ce0 => layer3_weights_13_ce0,
        q0 => layer3_weights_13_q0);

    layer3_weights_14_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_14
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_14_address0,
        ce0 => layer3_weights_14_ce0,
        q0 => layer3_weights_14_q0);

    layer3_weights_15_U : component nn_inference_nn_inference_Pipeline_col2_layer3_weights_15
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => layer3_weights_15_address0,
        ce0 => layer3_weights_15_ce0,
        q0 => layer3_weights_15_q0);

    flow_control_loop_pipe_sequential_init_U : component nn_inference_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter33_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    j_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln45_fu_571_p2 = ap_const_lv1_0))) then 
                    j_fu_96 <= add_ln45_fu_577_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_96 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
                ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
                ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
                ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
                ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
                ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
                ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                    j_1_cast_reg_684_pp0_iter10_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter9_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter11_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter10_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter12_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter11_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter13_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter12_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter14_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter13_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter15_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter14_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter16_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter15_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter17_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter16_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter18_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter17_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter19_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter18_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter20_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter19_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter21_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter20_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter22_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter21_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter23_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter22_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter24_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter23_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter25_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter24_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter26_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter25_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter27_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter26_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter28_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter27_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter29_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter28_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter2_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter1_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter30_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter29_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter31_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter30_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter32_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter31_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter33_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter32_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter3_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter2_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter4_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter3_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter5_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter4_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter6_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter5_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter7_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter6_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter8_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter7_reg(3 downto 0);
                    j_1_cast_reg_684_pp0_iter9_reg(3 downto 0) <= j_1_cast_reg_684_pp0_iter8_reg(3 downto 0);
                mul_i1_10_reg_934 <= grp_fu_1620_p_dout0;
                mul_i1_11_reg_954 <= grp_fu_1624_p_dout0;
                mul_i1_12_reg_974 <= grp_fu_1628_p_dout0;
                mul_i1_13_reg_994 <= grp_fu_1632_p_dout0;
                mul_i1_14_reg_1014 <= grp_fu_1636_p_dout0;
                mul_i1_1_reg_734 <= grp_fu_1580_p_dout0;
                mul_i1_2_reg_754 <= grp_fu_1584_p_dout0;
                mul_i1_3_reg_774 <= grp_fu_1588_p_dout0;
                mul_i1_4_reg_794 <= grp_fu_1592_p_dout0;
                mul_i1_5_reg_814 <= grp_fu_1596_p_dout0;
                mul_i1_6_reg_834 <= grp_fu_1600_p_dout0;
                mul_i1_7_reg_854 <= grp_fu_1604_p_dout0;
                mul_i1_8_reg_874 <= grp_fu_1608_p_dout0;
                mul_i1_9_reg_894 <= grp_fu_1612_p_dout0;
                mul_i1_reg_714 <= grp_fu_1576_p_dout0;
                mul_i1_s_reg_914 <= grp_fu_1616_p_dout0;
                sum_3_10_reg_949 <= grp_fu_1492_p_dout0;
                sum_3_11_reg_969 <= grp_fu_1496_p_dout0;
                sum_3_12_reg_989 <= grp_fu_1500_p_dout0;
                sum_3_13_reg_1009 <= grp_fu_1504_p_dout0;
                sum_3_1_reg_749 <= grp_fu_1452_p_dout0;
                sum_3_2_reg_769 <= grp_fu_1456_p_dout0;
                sum_3_3_reg_789 <= grp_fu_1460_p_dout0;
                sum_3_4_reg_809 <= grp_fu_1464_p_dout0;
                sum_3_5_reg_829 <= grp_fu_1468_p_dout0;
                sum_3_6_reg_849 <= grp_fu_1472_p_dout0;
                sum_3_7_reg_869 <= grp_fu_1476_p_dout0;
                sum_3_8_reg_889 <= grp_fu_1480_p_dout0;
                sum_3_9_reg_909 <= grp_fu_1484_p_dout0;
                sum_3_reg_729 <= grp_fu_1448_p_dout0;
                sum_3_s_reg_929 <= grp_fu_1488_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    j_1_cast_reg_684_pp0_iter1_reg(3 downto 0) <= j_1_cast_reg_684(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln45_fu_571_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    j_1_cast_reg_684(3 downto 0) <= j_1_cast_fu_583_p1(3 downto 0);
            end if;
        end if;
    end process;
    j_1_cast_reg_684(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter1_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter2_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter3_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter4_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter5_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter6_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter7_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter8_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter9_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter10_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter11_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter12_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter13_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter14_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter15_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter16_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter17_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter18_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter19_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter20_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter21_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter22_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter23_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter24_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter25_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter26_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter27_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter28_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter29_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter30_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter31_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter32_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    j_1_cast_reg_684_pp0_iter33_reg(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln45_fu_577_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state29_pp0_stage0_iter28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state30_pp0_stage0_iter29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state31_pp0_stage0_iter30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state32_pp0_stage0_iter31 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state33_pp0_stage0_iter32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state34_pp0_stage0_iter33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state35_pp0_stage0_iter34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln45_fu_571_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln45_fu_571_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter33_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter33_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_96, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_96;
        end if; 
    end process;

    grp_fu_1448_p_ce <= ap_const_logic_1;
    grp_fu_1448_p_din0 <= mul_i1_reg_714;
    grp_fu_1448_p_din1 <= ap_const_lv32_0;
    grp_fu_1448_p_opcode <= ap_const_lv2_0;
    grp_fu_1452_p_ce <= ap_const_logic_1;
    grp_fu_1452_p_din0 <= sum_3_reg_729;
    grp_fu_1452_p_din1 <= mul_i1_1_reg_734;
    grp_fu_1452_p_opcode <= ap_const_lv2_0;
    grp_fu_1456_p_ce <= ap_const_logic_1;
    grp_fu_1456_p_din0 <= sum_3_1_reg_749;
    grp_fu_1456_p_din1 <= mul_i1_2_reg_754;
    grp_fu_1456_p_opcode <= ap_const_lv2_0;
    grp_fu_1460_p_ce <= ap_const_logic_1;
    grp_fu_1460_p_din0 <= sum_3_2_reg_769;
    grp_fu_1460_p_din1 <= mul_i1_3_reg_774;
    grp_fu_1460_p_opcode <= ap_const_lv2_0;
    grp_fu_1464_p_ce <= ap_const_logic_1;
    grp_fu_1464_p_din0 <= sum_3_3_reg_789;
    grp_fu_1464_p_din1 <= mul_i1_4_reg_794;
    grp_fu_1464_p_opcode <= ap_const_lv2_0;
    grp_fu_1468_p_ce <= ap_const_logic_1;
    grp_fu_1468_p_din0 <= sum_3_4_reg_809;
    grp_fu_1468_p_din1 <= mul_i1_5_reg_814;
    grp_fu_1468_p_opcode <= ap_const_lv2_0;
    grp_fu_1472_p_ce <= ap_const_logic_1;
    grp_fu_1472_p_din0 <= sum_3_5_reg_829;
    grp_fu_1472_p_din1 <= mul_i1_6_reg_834;
    grp_fu_1472_p_opcode <= ap_const_lv2_0;
    grp_fu_1476_p_ce <= ap_const_logic_1;
    grp_fu_1476_p_din0 <= sum_3_6_reg_849;
    grp_fu_1476_p_din1 <= mul_i1_7_reg_854;
    grp_fu_1476_p_opcode <= ap_const_lv2_0;
    grp_fu_1480_p_ce <= ap_const_logic_1;
    grp_fu_1480_p_din0 <= sum_3_7_reg_869;
    grp_fu_1480_p_din1 <= mul_i1_8_reg_874;
    grp_fu_1480_p_opcode <= ap_const_lv2_0;
    grp_fu_1484_p_ce <= ap_const_logic_1;
    grp_fu_1484_p_din0 <= sum_3_8_reg_889;
    grp_fu_1484_p_din1 <= mul_i1_9_reg_894;
    grp_fu_1484_p_opcode <= ap_const_lv2_0;
    grp_fu_1488_p_ce <= ap_const_logic_1;
    grp_fu_1488_p_din0 <= sum_3_9_reg_909;
    grp_fu_1488_p_din1 <= mul_i1_s_reg_914;
    grp_fu_1488_p_opcode <= ap_const_lv2_0;
    grp_fu_1492_p_ce <= ap_const_logic_1;
    grp_fu_1492_p_din0 <= sum_3_s_reg_929;
    grp_fu_1492_p_din1 <= mul_i1_10_reg_934;
    grp_fu_1492_p_opcode <= ap_const_lv2_0;
    grp_fu_1496_p_ce <= ap_const_logic_1;
    grp_fu_1496_p_din0 <= sum_3_10_reg_949;
    grp_fu_1496_p_din1 <= mul_i1_11_reg_954;
    grp_fu_1496_p_opcode <= ap_const_lv2_0;
    grp_fu_1500_p_ce <= ap_const_logic_1;
    grp_fu_1500_p_din0 <= sum_3_11_reg_969;
    grp_fu_1500_p_din1 <= mul_i1_12_reg_974;
    grp_fu_1500_p_opcode <= ap_const_lv2_0;
    grp_fu_1504_p_ce <= ap_const_logic_1;
    grp_fu_1504_p_din0 <= sum_3_12_reg_989;
    grp_fu_1504_p_din1 <= mul_i1_13_reg_994;
    grp_fu_1504_p_opcode <= ap_const_lv2_0;
    grp_fu_1508_p_ce <= ap_const_logic_1;
    grp_fu_1508_p_din0 <= sum_3_13_reg_1009;
    grp_fu_1508_p_din1 <= mul_i1_14_reg_1014;
    grp_fu_1508_p_opcode <= ap_const_lv2_0;
    grp_fu_1576_p_ce <= ap_const_logic_1;
    grp_fu_1576_p_din0 <= temp_output2_0_load_1;
    grp_fu_1576_p_din1 <= layer3_weights_0_q0;
    grp_fu_1580_p_ce <= ap_const_logic_1;
    grp_fu_1580_p_din0 <= temp_output2_0_load_2;
    grp_fu_1580_p_din1 <= layer3_weights_1_q0;
    grp_fu_1584_p_ce <= ap_const_logic_1;
    grp_fu_1584_p_din0 <= temp_output2_0_load_3;
    grp_fu_1584_p_din1 <= layer3_weights_2_q0;
    grp_fu_1588_p_ce <= ap_const_logic_1;
    grp_fu_1588_p_din0 <= temp_output2_0_load_4;
    grp_fu_1588_p_din1 <= layer3_weights_3_q0;
    grp_fu_1592_p_ce <= ap_const_logic_1;
    grp_fu_1592_p_din0 <= temp_output2_0_load_5;
    grp_fu_1592_p_din1 <= layer3_weights_4_q0;
    grp_fu_1596_p_ce <= ap_const_logic_1;
    grp_fu_1596_p_din0 <= temp_output2_0_load_6;
    grp_fu_1596_p_din1 <= layer3_weights_5_q0;
    grp_fu_1600_p_ce <= ap_const_logic_1;
    grp_fu_1600_p_din0 <= temp_output2_0_load_7;
    grp_fu_1600_p_din1 <= layer3_weights_6_q0;
    grp_fu_1604_p_ce <= ap_const_logic_1;
    grp_fu_1604_p_din0 <= temp_output2_0_load_8;
    grp_fu_1604_p_din1 <= layer3_weights_7_q0;
    grp_fu_1608_p_ce <= ap_const_logic_1;
    grp_fu_1608_p_din0 <= temp_output2_0_load_9;
    grp_fu_1608_p_din1 <= layer3_weights_8_q0;
    grp_fu_1612_p_ce <= ap_const_logic_1;
    grp_fu_1612_p_din0 <= temp_output2_0_load_10;
    grp_fu_1612_p_din1 <= layer3_weights_9_q0;
    grp_fu_1616_p_ce <= ap_const_logic_1;
    grp_fu_1616_p_din0 <= temp_output2_0_load_11;
    grp_fu_1616_p_din1 <= layer3_weights_10_q0;
    grp_fu_1620_p_ce <= ap_const_logic_1;
    grp_fu_1620_p_din0 <= temp_output2_0_load_12;
    grp_fu_1620_p_din1 <= layer3_weights_11_q0;
    grp_fu_1624_p_ce <= ap_const_logic_1;
    grp_fu_1624_p_din0 <= temp_output2_0_load_13;
    grp_fu_1624_p_din1 <= layer3_weights_12_q0;
    grp_fu_1628_p_ce <= ap_const_logic_1;
    grp_fu_1628_p_din0 <= temp_output2_0_load_14;
    grp_fu_1628_p_din1 <= layer3_weights_13_q0;
    grp_fu_1632_p_ce <= ap_const_logic_1;
    grp_fu_1632_p_din0 <= temp_output2_0_load_15;
    grp_fu_1632_p_din1 <= layer3_weights_14_q0;
    grp_fu_1636_p_ce <= ap_const_logic_1;
    grp_fu_1636_p_din0 <= temp_output2_0_load_16;
    grp_fu_1636_p_din1 <= layer3_weights_15_q0;
    icmp_ln45_fu_571_p2 <= "1" when (ap_sig_allocacmp_j_1 = ap_const_lv4_A) else "0";
    j_1_cast_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_1),64));
    layer3_weights_0_address0 <= j_1_cast_fu_583_p1(4 - 1 downto 0);

    layer3_weights_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_0_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_10_address0 <= j_1_cast_reg_684_pp0_iter19_reg(4 - 1 downto 0);

    layer3_weights_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter20, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter20 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_10_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_11_address0 <= j_1_cast_reg_684_pp0_iter21_reg(4 - 1 downto 0);

    layer3_weights_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter22, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter22 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_11_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_12_address0 <= j_1_cast_reg_684_pp0_iter23_reg(4 - 1 downto 0);

    layer3_weights_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter24, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter24 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_12_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_13_address0 <= j_1_cast_reg_684_pp0_iter25_reg(4 - 1 downto 0);

    layer3_weights_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter26, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_13_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_14_address0 <= j_1_cast_reg_684_pp0_iter27_reg(4 - 1 downto 0);

    layer3_weights_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter28, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1))) then 
            layer3_weights_14_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_15_address0 <= j_1_cast_reg_684_pp0_iter29_reg(4 - 1 downto 0);

    layer3_weights_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter30, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter30 = ap_const_logic_1))) then 
            layer3_weights_15_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_1_address0 <= j_1_cast_reg_684_pp0_iter1_reg(4 - 1 downto 0);

    layer3_weights_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_1_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_2_address0 <= j_1_cast_reg_684_pp0_iter3_reg(4 - 1 downto 0);

    layer3_weights_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_2_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_3_address0 <= j_1_cast_reg_684_pp0_iter5_reg(4 - 1 downto 0);

    layer3_weights_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_3_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_4_address0 <= j_1_cast_reg_684_pp0_iter7_reg(4 - 1 downto 0);

    layer3_weights_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_4_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_5_address0 <= j_1_cast_reg_684_pp0_iter9_reg(4 - 1 downto 0);

    layer3_weights_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter10, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_5_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_6_address0 <= j_1_cast_reg_684_pp0_iter11_reg(4 - 1 downto 0);

    layer3_weights_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_6_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_7_address0 <= j_1_cast_reg_684_pp0_iter13_reg(4 - 1 downto 0);

    layer3_weights_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_7_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_8_address0 <= j_1_cast_reg_684_pp0_iter15_reg(4 - 1 downto 0);

    layer3_weights_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter16, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_8_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    layer3_weights_9_address0 <= j_1_cast_reg_684_pp0_iter17_reg(4 - 1 downto 0);

    layer3_weights_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter18, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter18 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            layer3_weights_9_ce0 <= ap_const_logic_1;
        else 
            layer3_weights_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    temp_output3_0_address0 <= j_1_cast_reg_684_pp0_iter33_reg(4 - 1 downto 0);

    temp_output3_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            temp_output3_0_ce0 <= ap_const_logic_1;
        else 
            temp_output3_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    temp_output3_0_d0 <= grp_fu_1508_p_dout0;

    temp_output3_0_we0_assign_proc : process(ap_enable_reg_pp0_iter34, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter34 = ap_const_logic_1))) then 
            temp_output3_0_we0 <= ap_const_logic_1;
        else 
            temp_output3_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
